on:
  issue_comment:
    types:
      - created
jobs:
  echo_issue_comment:
    runs-on: ubuntu-latest
    name: profanity check
    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Profanity check step
        uses: ./ # Uses an action in the root directory
        id: check
        with:
          author: ${{ github.event.comment.user.login }}
          comment: ${{ github.event.comment.body }}

