on:
  issue_comment:
    types:
      - created
jobs:
  echo_issue_comment:
    runs-on: ubuntu-latest
    name: Echo issue comment
    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Echo issue comment step
        uses: ./ # Uses an action in the root directory
        id: echo
        with:
          author: 'John Doe'
          comment: 'How are you?'
      - name: Get the output
        run: echo "${{ steps.echo.outputs.who }} said ${{ steps.echo.outputs.what }} at ${{ steps.echo.outputs.when }}"